### ISSUE TITLE
Add ksqlDB-server and the CLI into KRaft cp-all-in-one-kraft

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/cp-all-in-one#101]
**Description**
Add ksqlDB-server and the CLI into KRaft cp-all-in-one-kraft

There is a technical reason why ksqlDB didn't work initially with the KRaft config a few releases ago, but unfortunately I don't recall what that reason was.  It's important to try it again and resolve any issue that prevented it from working.

**Comment by ybyzek** [comment]
In progress

**Comment by sparrowV** [comment]
@ybyzek  can you also please add multi node example? There is just one node in the example
