### ISSUE TITLE
is that free to use confluentinc/cp-all-in-one images in official laptops?

### ISSUE THREAD

**Issue by PrabaharanK** [confluentinc/cp-all-in-one#21]
I'm new to kafka, I checkout github  **confluentinc/cp-all-in-one** docker base branch and started using broker, zookeeper and control center images in my official laptop. I'm using this images for my local development.  One of my friend told that confluent kafka is not free and we should not use them in our official laptops (especially control-center image) . He said we should use apache kafka for our local. 

Is that free to use **confluentinc/cp-all-in-one** docker images in our official laptops or do we need get the paid license to use them in official laptops.

**Comment by ybyzek** [comment]
@PrabaharanK usage of confluentinc/cp-all-in-one is free on your laptop is free because it is covered by the Developer License.  Please see https://docs.confluent.io/current/control-center/installation/licenses.html#cp-developer-license for more details.
