### ISSUE TITLE
Unable to query the Streams

### ISSUE THREAD

**Issue by shansara-ghub** [confluentinc/cp-all-in-one#45]
I have setup the Cluster using the cp-all-in-one source via docker.
But while querying the streams I get the error "An unknown error has occurred. Check the connection settings." . Can you advice what could be wrong ?

![image](https://user-images.githubusercontent.com/70953454/97100963-798ca580-1699-11eb-955c-947d8c2feaae.png)

Please find the dump of the cluster settings - broker_config.txt (renamed the file to txt as the filename with the json extension couldn't be uploaded. The contents of the file are not modified).

[broker_config.txt](https://github.com/confluentinc/cp-all-in-one/files/5434274/broker_config.txt)

Here are the few more Control Center screenshots for reference -
![image](https://user-images.githubusercontent.com/70953454/97101031-164f4300-169a-11eb-9988-8caca8b9d9d8.png)

![image](https://user-images.githubusercontent.com/70953454/97101048-37b02f00-169a-11eb-8b5c-469bc4d5b348.png)

![image](https://user-images.githubusercontent.com/70953454/97101061-531b3a00-169a-11eb-9220-bbe65f6e5d45.png)

![image](https://user-images.githubusercontent.com/70953454/97101067-65957380-169a-11eb-9434-c94bd1c7bf68.png)

**Comment by shansara-ghub** [comment]
Update -
Able to query the streams "pageviews" from the KSQLDB CLI 

![image](https://user-images.githubusercontent.com/70953454/97101754-3da90e80-16a0-11eb-8e4a-538a0c7414e8.png)

But it is just that from UI I keep getting the error 
![image](https://user-images.githubusercontent.com/70953454/97101797-911b5c80-16a0-11eb-9771-61e8a4156130.png)

**Comment by ybyzek** [comment]
@shansara-ghub can you please try again with `EMIT CHANGES` appended at the end?  The CLI screenshot used it but the C3 UI screenshot did not

**Comment by shansara-ghub** [comment]
Hi @ybyzek - Really appreciate your response on a Sunday 👍 
Yes I did try the query with EMIT CHANGES but still get the same error. Please see below -

![image](https://user-images.githubusercontent.com/70953454/97107772-8e812d00-16c9-11eb-9163-194054bc3c68.png)

**Comment by ybyzek** [comment]
@shansara-ghub 👍 thanks for checking.  

1. Can you capture the logs to determine if there any messages with more specific errors (e.g. `docker-compose logs ksqldb-server`, `docker-compose logs control-center`).
2. Is `cp-all-in-one` running exactly as shown in GitHub, unmodified?  That works in my environment, so it's curious it's failing in your environment.

**Comment by shansara-ghub** [comment]
Hi @ybyzek , 
Yes the cp-all-in-one is running without any modification. 

Please find attached the logs. 
[logs.zip](https://github.com/confluentinc/cp-all-in-one/files/5435964/logs.zip)

I see some errors in the logs like below, but I'm not sure if this could be the problem ?
ksqldb-server      | [2020-10-25 07:53:28,012] INFO [Consumer clientId=_confluent-ksql-default_transient_2595051019282980993_1603612407807-dc77c738-0b3c-4486-946f-df690deb80ca-StreamThread-2-consumer, groupId=_confluent-ksql-default_transient_2595051019282980993_1603612407807] Join group failed with org.apache.kafka.common.errors.MemberIdRequiredException: The group member needs to have a valid member id before actually entering a consumer group. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)

ksqldb-server      | [2020-10-25 07:53:27,898] WARN The configuration 'ksql.logger.production.error' was supplied but isn't a known config. (org.apache.kafka.clients.producer.ProducerConfig)

**Comment by berthayes** [comment]
Hi, @shansara-ghub .  I see this all the time - the issue is in the docker-compose.yml file that advertises KSQL to Control Center:
`      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"`

If you're NOT running docker-compose on localhost (I often run the whole CP docker stack on a separate system), then your browser will have nothing to connect to on localhost.  I have solved this for myself by editing the line above to:
`      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://your.accessible.host:8088"`

Hope this helps.

-Bert

**Comment by shansara-ghub** [comment]
Hi @berthayes , Spot on. That has resolved the issue.
