### ISSUE TITLE
Unable to run docker-compose up due to missing image: cp-ksql-server:5.5.0

### ISSUE THREAD

**Issue by rob3000** [confluentinc/cp-all-in-one#5]
Following the instructions from: https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html and checking out branch `5.5.0-post` when running `docker-compose up -d --build` it fails to build/fetch the image `confluentinc/cp-ksql-server:5.5.0` Due to the image not being present on docker hub: https://hub.docker.com/r/confluentinc/cp-ksql-server/tags?page=1&ordering=name

**Comment by ybyzek** [comment]
@rob3000 per https://github.com/confluentinc/cp-all-in-one/blob/5.5.0-post/cp-all-in-one/docker-compose.yml#L113 , it should be pulling `cp-ksqldb-server`, not `cp-ksql-server`.  And the `5.5.0` tag does exist for `cp-ksqldb-server`: https://hub.docker.com/r/confluentinc/cp-ksqldb-server/tags?page=1&ordering=name .  Can you please verify the Docker compose file you are using?

**Comment by rob3000** [comment]
Thanks @ybyzek My apologies!
