### ISSUE TITLE
The container name "/zookeeper" already in use

### ISSUE THREAD

**Issue by lplaetevoet** [confluentinc/cp-all-in-one#55]
**Description**
I followed the tutorial https://docs.confluent.io/platform/current/quickstart/ce-docker-quickstart.html#ce-docker-quickstart to the letter.

It fails at the beginning, step 4: `docker-compose up -d` brings:

``` 
Creating zookeeper ... error

ERROR: for zookeeper  Cannot create container for service zookeeper: Conflict. The container name "/zookeeper" is already in use by container "cb780502175d907a0d654f62dc5010410e5b2493a6bf475019164898ec13ef1e". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for zookeeper  Cannot create container for service zookeeper: Conflict. The container name "/zookeeper" is already in use by container "cb780502175d907a0d654f62dc5010410e5b2493a6bf475019164898ec13ef1e". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
```
But nothing is started, `docker-compose ps` or `docker ps` are empty

**Troubleshooting**

```
$ docker-compose logs cb780502175d907a0d654f62dc5010410e5b2493a6bf475019164898ec13ef1e

ERROR: No such service: cb780502175d907a0d654f62dc5010410e5b2493a6bf475019164898ec13ef1e
``` 

**Environment**
 - GitHub branch: `6.0.1-post`
 - Operating System: macOS Big Sur version 11.0.1
 - Version of Docker: Docker version 19.03.13, build 4484c46d9d
 - Version of Docker Compose: docker-compose version 1.27.4, build 40524192

**Comment by ybyzek** [comment]
@lplaetevoet output suggests another Docker container running ZooKeeper.  Please use the `docker` commands to identify all the containers running, e.g. `docker container ls -a`, `docker container ls cb780502175d907a0d654f62dc5010410e5b2493a6bf475019164898ec13ef1e`.
