### ISSUE TITLE
Use consistent image references for services in cp-all-in-one yaml 

### ISSUE THREAD

**Issue by holgerbrandl** [confluentinc/cp-all-in-one#6]
In `cp-all-in-one/docker-compose.yml` all services except connect use a consistent image reference of the form:
> image: ${REPOSITORY}/<<SERVICE_NAME>>:${CONFLUENT_DOCKER_TAG}

Why connect is using `cnfldemos/cp-server-connect-datagen:0.2.0-5.4.0` instead should be documented/clarified or fixed to provide a consistent setup (i.e. to enable a version increment by simply changing the `CONFLUENT_DOCKER_TAG` in the `.env`

**Comment by ybyzek** [comment]
All image names are now explicitly defined
